### ISSUE TITLE
Problema di conversione date

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/RaveraArianna#1]
Apro questa issue per discutere il problema che hai avuto con le date. Voglio riuscire a chiarirlo per bene e risolverlo. Usiamo la issue per discuterne.
Prima di tutto è un funzionamento purtroppo noto da tempo. Vedi: https://bugs.mysql.com/bug.php?id=71084 (è un bug del 2013). Ad un certo punto dice:
```
Another issue [...] the methods get/setDate() without Calendar argument not only perform the time zone correction but also truncate time info, so as in your example:
   - '2013-11-20' >(tz correction)> '2013-11-19 23:00:00.0' >(truncate)> '2013-11-19' > stored in server.
   - get from server '2013-11-19' >(tz correction)> '2013-11-19 1:00:00.0' >(truncate)> '2013-11-19'
```
che mi pare che sia proprio il "nostro" problema. 

Sono riuscito a riprodurlo con un programmino di esempio, in cui si vede che (attivando il LOG delle Query di MariaDB: https://mariadb.com/kb/en/library/general-query-log/):
```
Console di Eclipse: Cerco tra date 2019-05-17 e 2019-05-19
Log di MariaDB: SELECT * FROM giorni WHERE giorni.giorno>='2019-05-16' AND giorni.giorno<='2019-05-18'
```

Su StackOverflow un tizio suggerisce (https://stackoverflow.com/a/53093002/986709) di usare `st.setObject(1,  data1);`, passando direttamente una LocalDate come Object (e non un setDate). L'ho provato, ma nel mio programmino di prova non cambia nulla...

**Comment by fulcorno** [comment]
Ho trovato una soluzione possibile: **usare il JDBC Connector di MariaDB e non quello di MySQL**!
Vai su: https://mariadb.com/kb/en/library/about-mariadb-connector-j/
e scarica il _Java 8 connector_, sostituendo `mariadb-java-client-2.4.1.jar` al posto del (maledetto) `mysql-connector-java-8.0.15.jar`.
Per magia tutto funziona. Si può anche togliere il parametro `?serverTimezone=UTC` nella stringa di connessione.
Puoi provare con il tuo progetto e verificare se risolve?

**Comment by ariannaravera** [comment]
Perfetto, funziona tutto.
Grazie molte!
