### ISSUE TITLE
dump database incompleto

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/RaveraArianna#3]
nel progetto consegnato, i file SQL sono incompleti (contengono solo INSERT INTO in tabelle che però non sono definite con le istruzioni CREATE TABLE). In questo modo non riesco a ricreare il database e dunque a ri-eseguire il tuo programma.

Ti chiedo di rifare l'esportazione del database in modo più completo (includendo le CREATE TABLE e magari anche la CREATE DATABASE) ed aggiornare il repository, in modo che io possa concludere la valutazione.

**Comment by ariannaravera** [comment]
Ho aggiornato il database da sue indicazioni, ora dovrebbe essere completo ma attendo sua conferma.

Molte grazie!
